[workspace]
resolver = "2"
members = ["crates/kagaz-core", "crates/kagaz-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/yagyaanshK/kagaz"
authors = ["Yagyaansh Khaneja"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
